


import { Difficulty, Stance, Trick, TrickCategory, TrickTip } from "./types";

export const SKATE_LETTERS = ['S', 'K', 'A', 'T', 'E'];

export const TRANSLATIONS = {
  EN: {
    NEW_SESSION: "New Session",
    CUSTOMIZED_TRAINING: "Customized Training",
    TOTAL_LANDED: "Total Landed",
    AVG_SUCCESS: "Avg Success",
    PROGRESSION: "Progression (Last 10)",
    SETUP_SESSION: "Setup Session",
    SESSION_LENGTH: "Session Length",
    DIFFICULTY: "Difficulty",
    AI_COACH_MODE: "AI Coach Mode",
    CATEGORIES: "Categories",
    STANCES: "Stances",
    STANCE_MIX: "Stance Mix Settings",
    START_SKATING: "Start Skating",
    GENERATING: "Generating Session...",
    TRICK_COUNTER: "Trick",
    ABORT: "Abort",
    GET_TIP: "Get a Tip",
    ASKING_COACH: "Asking Coach...",
    PRO_TIP: "Pro Tip",
    FAILED: "Failed",
    LANDED: "Landed",
    SESSION_COMPLETE: "Session Complete",
    COMPLETED: "Completed",
    CLEAN_SHEET: "Clean Sheet",
    AI_FEEDBACK: "AI Coach Feedback",
    DETAILS: "Details",
    DASHBOARD: "Dashboard",
    ANALYTICS: "Analytics",
    SUCCESS: "Success",
    SOURCE: "Source",
    VIDEO: "Video",
    // Analytics
    TOTAL_SESSIONS: "Total Sessions",
    BEST_STREAK: "Best Streak",
    WEAKNESS_ANALYSIS: "Weakness Analysis",
    RECOMMENDED_PRACTICE: "Recommended Practice",
    STATS: "Stats",
    PRACTICE_MORE: "Practice more!",
    COMPREHENSIVE_DIAGNOSIS: "Comprehensive Diagnosis",
    SESSION_SUMMARY: "Session Analysis Summary",
    KEY_WEAKNESSES: "Key Weaknesses",
    IMPROVEMENT_DIRECTIONS: "Improvement Suggestions",
    AI_COACH_FEEDBACK_TITLE: "AI Coach Feedback",
    GENERATE_INSIGHT: "Generate AI Diagnosis",
    GENERATING_INSIGHT: "Analyzing Data...",
    SHARE_STORY: "Share to Instagram",
    SHARING: "Capturing...",
    // Values
    Easy: "Easy",
    Medium: "Medium",
    Hard: "Hard",
    Pro: "Pro",
    Flatground: "Flatground",
    Grind: "Grind",
    Transition: "Transition",
    Regular: "Regular",
    Goofy: "Goofy",
    Fakie: "Fakie",
    Switch: "Switch",
    Nollie: "Nollie",
    AI_PLACEHOLDER: "e.g. 'Backside pop tricks' or 'Focus on pop height'",
    CONFIRM_ABORT: "End current session? Progress will be lost.",
    // Learning
    LEARNING: "Trick Guide",
    PRACTICE_THIS: "Practice Trick",
    HOW_TO: "How To",
    ANALYZING: "Analyzing session data...",
    DESCRIPTION: "Description",
    VIDEO_TUTORIAL: "Video Tutorial",
    // Profile & Experience
    DAYS_SKATING: "Days Skating",
    START_DATE: "Start Date",
    SET_START_DATE: "Set Start Date",
    SAVE: "Save",
    CANCEL: "Cancel",
    DAY: "Day",
    EXPERIENCE_LEVEL: "Experience Level",
    LEVEL_BEGINNER: "Beginner",
    LEVEL_INTERMEDIATE: "Amateur",
    LEVEL_ADVANCED: "Pro",
    LEVEL_REQ_PRO: "Approval Required",
    REQUEST_PRO: "Request Pro Verification",
    REQUEST_PENDING: "Under Review",
    // Ranking
    GLOBAL_RANKING: "Global Ranking",
    YOUR_TIER: "Your Tier",
    TOP_PERCENT: "Top",
    TIER_1: "Street Rat",
    TIER_2: "Local Hero",
    TIER_3: "Sponsored Am",
    TIER_4: "G.O.A.T",
    RANKING_DESC: "Based on Hard/Pro tricks landed",
    // Auth
    LOGIN_GOOGLE: "Sign in with Google",
    LOGOUT: "Logout",
    GUEST: "Guest",
    // Tips
    TIP_VARIATION_STANDARD: "Standard",
    TIP_VARIATION_FAKIE: "Fakie Variation",
    TIP_VARIATION_NOLLIE: "Nollie Variation",
    TIP_VARIATION_SWITCH: "Switch Variation",
    // Game
    LAST_CHANCE: "Last Try! (Rebate)",
    // AI Vision
    AI_VISION_TITLE: "AI Vision",
    AI_VISION_DESC: "Upload a photo or video to analyze your trick.",
    UPLOAD_MEDIA: "Upload Media",
    ANALYZE_TRICK: "Analyze Trick",
    ANALYZING_MEDIA: "Tracking Skater & Board...",
    TRICK_DETECTED: "Trick Detected",
    FORM_SCORE: "Form Score",
    HEIGHT_EST: "Est. Height",
    POSTURE_ANALYSIS: "Posture Analysis",
    LANDING_ANALYSIS: "Landing Analysis",
    IMPROVEMENT_TIP: "Coach Tip",
    FILE_TOO_LARGE: "File is too large. Please use video under 20MB.",
    ENTER_TRICK_NAME: "Trick Name (Optional)",
    TRICK_NAME_DESC: "Providing the trick name helps accuracy. If left blank, AI may guess incorrectly.",
    WRONG_ANALYSIS: "Report Issue",
    PROVIDE_FEEDBACK: "Help us improve. What was wrong?",
    ACTUAL_TRICK_NAME: "Actual Trick Name",
    ACTUAL_HEIGHT: "Actual Height (e.g. 50cm)",
    SEND_FEEDBACK: "Send Feedback",
    FEEDBACK_THANKS: "Thanks! We'll learn from this.",
    SELECT_YOUR_STANCE: "Select Your Stance",
    SELECT_STANCE_DESC: "Essential for detecting Fakie, Nollie, and Switch.",
    TRACKING_BOARD: "Tracking Board Physics..."
  },
  KR: {
    NEW_SESSION: "새로운 세션",
    CUSTOMIZED_TRAINING: "맞춤형 훈련 설정",
    TOTAL_LANDED: "성공 횟수",
    AVG_SUCCESS: "평균 성공률",
    PROGRESSION: "성장 그래프 (최근 10회)",
    SETUP_SESSION: "세션 설정",
    SESSION_LENGTH: "트릭 개수",
    DIFFICULTY: "난이도",
    AI_COACH_MODE: "AI 코치 모드",
    CATEGORIES: "카테고리",
    STANCES: "스탠스",
    STANCE_MIX: "스탠스 믹스",
    START_SKATING: "세션 시작",
    GENERATING: "루틴 짜는 중...",
    TRICK_COUNTER: "트릭",
    ABORT: "그만하기",
    GET_TIP: "팁 보기",
    ASKING_COACH: "코치에게 물어보는 중...",
    PRO_TIP: "프로 팁",
    FAILED: "실패",
    LANDED: "성공",
    SESSION_COMPLETE: "세션 종료",
    COMPLETED: "완료",
    CLEAN_SHEET: "퍼펙트 게임",
    AI_FEEDBACK: "AI 코치 피드백",
    DETAILS: "상세 기록",
    DASHBOARD: "홈",
    ANALYTICS: "분석실",
    SUCCESS: "성공",
    SOURCE: "출처",
    VIDEO: "영상",
    // Analytics
    TOTAL_SESSIONS: "총 세션 횟수",
    BEST_STREAK: "최고 연승",
    WEAKNESS_ANALYSIS: "집중 공략 포인트",
    RECOMMENDED_PRACTICE: "추천 연습 메뉴",
    STATS: "통계",
    PRACTICE_MORE: "연습이 더 필요해요!",
    COMPREHENSIVE_DIAGNOSIS: "종합 진단 리포트",
    SESSION_SUMMARY: "세션 요약",
    KEY_WEAKNESSES: "주요 약점",
    IMPROVEMENT_DIRECTIONS: "솔루션",
    AI_COACH_FEEDBACK_TITLE: "AI 코치 피드백",
    GENERATE_INSIGHT: "AI 진단 받기",
    GENERATING_INSIGHT: "데이터 분석 중...",
    SHARE_STORY: "인스타 스토리 공유",
    SHARING: "캡처 중...",
    // Values
    Easy: "입문",
    Medium: "중급",
    Hard: "상급",
    Pro: "프로",
    Flatground: "플랫",
    Grind: "그라인드",
    Transition: "트랜지션",
    Regular: "레귤러",
    Goofy: "구피",
    Fakie: "페이키",
    Switch: "스위치",
    Nollie: "널리",
    AI_PLACEHOLDER: "예: '팝을 뒷방향으로 차는 연습' 또는 '알리 높이 높이기'",
    CONFIRM_ABORT: "세션을 종료하시겠어요? 기록이 저장되지 않습니다.",
    // Learning
    LEARNING: "트릭 가이드",
    PRACTICE_THIS: "트릭 연습하기",
    HOW_TO: "배우는 법",
    ANALYZING: "데이터 분석 중...",
    DESCRIPTION: "기술 설명",
    VIDEO_TUTORIAL: "영상 강의",
    // Profile & Experience
    DAYS_SKATING: "스케이트 라이프",
    START_DATE: "시작일",
    SET_START_DATE: "시작일 설정",
    SAVE: "저장",
    CANCEL: "취소",
    DAY: "일차",
    EXPERIENCE_LEVEL: "레벨",
    LEVEL_BEGINNER: "비기너",
    LEVEL_INTERMEDIATE: "아마추어",
    LEVEL_ADVANCED: "프로",
    LEVEL_REQ_PRO: "프로 승인 필요",
    REQUEST_PRO: "프로 승인 신청",
    REQUEST_PENDING: "심사 중",
    // Ranking
    GLOBAL_RANKING: "글로벌 랭킹",
    YOUR_TIER: "현재 티어",
    TOP_PERCENT: "상위",
    TIER_1: "스트릿 랫",
    TIER_2: "로컬 히어로",
    TIER_3: "스폰서드",
    TIER_4: "G.O.A.T",
    RANKING_DESC: "상급/프로 기술 성공 횟수 기준",
    // Auth
    LOGIN_GOOGLE: "구글 계정으로 시작하기",
    LOGOUT: "로그아웃",
    GUEST: "게스트",
    // Tips
    TIP_VARIATION_STANDARD: "기본",
    TIP_VARIATION_FAKIE: "페이키",
    TIP_VARIATION_NOLLIE: "널리",
    TIP_VARIATION_SWITCH: "스위치",
    // Game
    LAST_CHANCE: "마지막 기회! (리베이트)",
    // AI Vision
    AI_VISION_TITLE: "AI 비전",
    AI_VISION_DESC: "영상이나 사진을 올리면 AI가 자세를 분석해드립니다.",
    UPLOAD_MEDIA: "미디어 업로드",
    ANALYZE_TRICK: "트릭 분석하기",
    ANALYZING_MEDIA: "스케이터와 보드를 추적 중...",
    TRICK_DETECTED: "감지된 트릭",
    FORM_SCORE: "자세 점수",
    HEIGHT_EST: "예상 높이",
    POSTURE_ANALYSIS: "자세 분석",
    LANDING_ANALYSIS: "랜딩 분석",
    IMPROVEMENT_TIP: "코치 팁",
    FILE_TOO_LARGE: "파일이 너무 큽니다. 20MB 이하의 영상을 사용해주세요.",
    ENTER_TRICK_NAME: "기술 이름 (선택사항)",
    TRICK_NAME_DESC: "기술 이름을 적어주시면 더 정확하게 분석됩니다. 비워두면 AI가 잘못 인식할 수 있습니다.",
    WRONG_ANALYSIS: "결과가 다른가요?",
    PROVIDE_FEEDBACK: "AI 학습을 위해 정확한 정보를 알려주세요.",
    ACTUAL_TRICK_NAME: "실제 기술 이름",
    ACTUAL_HEIGHT: "실제 높이 (예: 50cm)",
    SEND_FEEDBACK: "피드백 보내기",
    FEEDBACK_THANKS: "피드백 감사합니다! 학습에 반영하겠습니다.",
    SELECT_YOUR_STANCE: "내 스탠스 선택",
    SELECT_STANCE_DESC: "페이키, 널리, 스위치를 구분하기 위해 꼭 필요합니다.",
    TRACKING_BOARD: "보드 물리엔진 분석 중..."
  }
};

export const BASE_TRICKS: Trick[] = [
  // Easy (Basic)
  { id: 'ollie', name: 'Ollie', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=arQV9_seXl0', description: { EN: "The foundation of street skating. Pop the tail and slide your front foot up.", KR: "스케이트보딩의 가장 기본이 되는 기술입니다. 테일을 팝하고 앞발을 끌어올려 점프합니다." } },
  { id: 'shuvit', name: 'Shuvit', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=4270O2pD9Rg', description: { EN: "Spin the board 180 degrees without popping.", KR: "팝 없이 보드만 180도 회전시키는 기술입니다." } },
  { id: 'fs-180', name: 'Frontside 180', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=_4O9Lh5x80s', description: { EN: "Rotate your body and board 180 degrees facing forward.", KR: "몸과 보드를 앞쪽 방향으로 180도 회전합니다." } },
  { id: 'bs-180', name: 'Backside 180', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=HchYqOXy8JI', description: { EN: "Rotate your body and board 180 degrees with your back leading.", KR: "등을 진행 방향으로 돌리며 180도 회전합니다." } },
  { id: 'fakie-ollie', name: 'Fakie Ollie', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=l4qJv5h8Wvw', description: { EN: "An ollie while rolling backwards.", KR: "뒤로 가는 상태(페이키)에서 하는 알리입니다." } },
  { id: 'nollie', name: 'Nollie', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=kYv95J6wQ0I', description: { EN: "Popping with the nose while rolling forward.", KR: "주행 중 노즈를 팝하여 점프하는 기술입니다." } },
  { id: 'pop-shuvit', name: 'Pop Shuvit', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=vA1EPid4aiw', description: { EN: "Spin the board 180 degrees with a pop.", KR: "테일을 팝하면서 보드를 180도 회전시킵니다." } },
  { id: 'fs-pop-shuvit', name: 'Frontside Pop Shuvit', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=nEcssJ5_xK4', description: { EN: "Spin the board 180 degrees frontside with a pop.", KR: "보드를 등 뒤쪽으로 180도 회전시킵니다." } },
  { id: 'fakie-shuvit', name: 'Fakie Shuvit', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=GkC5Rmv5_6o', description: { EN: "Shuvit while riding backwards.", KR: "페이키 상태에서 하는 셔빗입니다." } },
  { id: 'manual', name: 'Manual', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=A_2t5_n7yJc', description: { EN: "Balancing on the back wheels.", KR: "뒷바퀴로만 중심을 잡고 주행하는 기술입니다." } },
  { id: 'nose-manual', name: 'Nose Manual', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=1dJjPjjW5QA', description: { EN: "Balancing on the front wheels.", KR: "앞바퀴로만 중심을 잡고 주행합니다." } },
  { id: 'boneless', name: 'Boneless', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=M5FzOq_XJc8', description: { EN: "Plant your front foot and grab the board.", KR: "앞발을 땅에 짚고 보드를 손으로 잡고 점프합니다." } },
  { id: 'no-comply', name: 'No Comply 180', category: TrickCategory.FLATGROUND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=yY1X_tgJ8c8', description: { EN: "Plant front foot, pop the board 180.", KR: "앞발을 땅에 짚고 뒷발로 보드를 팝하여 180도 돌립니다." } },
  { id: 'boardslide', name: 'Boardslide', category: TrickCategory.GRIND, difficulty: Difficulty.EASY, videoUrl: 'https://www.youtube.com/watch?v=7M0fS9iOq_o', description: { EN: "Slide the middle of your board on a rail or ledge.", KR: "레일이나 렛지 위를 보드 중간으로 미끄러집니다." } },

  // Medium (Intermediate)
  { id: 'kickflip', name: 'Kickflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=rCJoTnMP16M', description: { EN: "Flip the board with your toe.", KR: "알리를 하며 앞발가락으로 보드를 차서 회전시킵니다." } },
  { id: 'heelflip', name: 'Heelflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=339k4XEvbxY', description: { EN: "Flip the board with your heel.", KR: "앞발 뒤꿈치로 보드를 차서 반대 방향으로 회전시킵니다." } },
  { id: 'varial-kickflip', name: 'Varial Kickflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=MfIkBXXZrEY', description: { EN: "Pop shuvit mixed with a kickflip.", KR: "팝샤빗과 킥플립을 동시에 하는 기술입니다." } },
  { id: 'varial-heelflip', name: 'Varial Heelflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=iX61qqQvQkM', description: { EN: "Frontside shuvit mixed with a heelflip.", KR: "프론트사이드 셔빗과 힐플립을 섞은 기술입니다." } },
  { id: 'half-cab', name: 'Half Cab', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=II6v_5c4i9g', description: { EN: "Fakie backside 180.", KR: "페이키 상태에서 백사이드로 180도 회전합니다." } },
  { id: 'fakie-bigspin', name: 'Fakie Bigspin', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=KjYk4tK5L8c', description: { EN: "Fakie 360 shuvit with a 180 body varial.", KR: "페이키 상태에서 보드는 360도, 몸은 180도 회전합니다." } },
  { id: 'nollie-pop-shuvit', name: 'Nollie Pop Shuvit', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=0w5_v0g5_0k', description: { EN: "Pop shuvit from the nose.", KR: "노즈를 팝하여 하는 팝샤빗입니다." } },
  { id: 'fs-kickflip', name: 'Frontside Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=uK4WJ7P6t5E', description: { EN: "Kickflip while doing a frontside 180.", KR: "프론트사이드 180과 킥플립을 동시에 합니다." } },
  { id: 'bs-kickflip', name: 'Backside Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=D-4z2t2f_kE', description: { EN: "Kickflip while doing a backside 180.", KR: "백사이드 180과 킥플립을 동시에 합니다." } },
  { id: 'fs-heelflip', name: 'Frontside Heelflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=2zW_6y3y_yE', description: { EN: "Heelflip while doing a frontside 180.", KR: "프론트사이드 180과 힐플립을 동시에 합니다." }, 
    stanceDocs: { 
        [Stance.FAKIE]: { videoUrl: 'https://www.youtube.com/watch?v=mYcViRQRoH4', description: { EN: "Fakie Frontside Heelflip", KR: "페이키 프론트사이드 힐플립 튜토리얼입니다." } }
    } 
  },
  { id: 'bs-heelflip', name: 'Backside Heelflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.MEDIUM, description: { EN: "Heelflip while doing a backside 180.", KR: "백사이드 180과 힐플립을 동시에 합니다." } },
  { id: '50-50', name: '50-50 Grind', category: TrickCategory.GRIND, difficulty: Difficulty.MEDIUM, videoUrl: 'https://www.youtube.com/watch?v=hpzC9tXz8g8', description: { EN: "Grind on both trucks.", KR: "두 트럭 모두 레일이나 렛지에 걸고 그라인드합니다." } },
  { id: '5-0', name: '5-0 Grind', category: TrickCategory.GRIND, difficulty: Difficulty.MEDIUM, description: { EN: "Grind only on the back truck.", KR: "뒷 트럭으로만 그라인드하고 앞바퀴는 듭니다." } },
  { id: 'nosegrind', name: 'Nosegrind', category: TrickCategory.GRIND, difficulty: Difficulty.MEDIUM, description: { EN: "Grind only on the front truck.", KR: "앞 트럭으로만 그라인드합니다." } },
  
  // Hard (Advanced)
  { id: 'treflip', name: '360 Flip (Tre Flip)', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, videoUrl: 'https://www.youtube.com/watch?v=XGw3YkQmNig', description: { EN: "360 shuvit mixed with a kickflip.", KR: "보드를 360도 돌리면서 동시에 킥플립을 합니다. 스케이터들의 로망 기술입니다." } },
  { id: 'laserflip', name: 'Laser Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "Frontside 360 shuvit mixed with a heelflip.", KR: "프론트사이드 360 셔빗과 힐플립을 섞은 고난도 기술입니다." } },
  { id: 'hardflip', name: 'Hardflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, videoUrl: 'https://www.youtube.com/watch?v=subb5N6_a68', description: { EN: "Frontside pop shuvit mixed with a kickflip, creates an illusion.", KR: "프론트사이드 팝샤빗과 킥플립의 조합으로, 다리 사이로 보드가 세워져서 돕니다." } },
  { id: 'inward-heelflip', name: 'Inward Heelflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "Backside pop shuvit mixed with a heelflip.", KR: "백사이드 팝샤빗과 힐플립을 섞은 기술입니다." } },
  { id: 'bigspin', name: 'Bigspin', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "360 shuvit while your body does a 180.", KR: "보드는 360도 돌고, 몸은 같은 방향으로 180도 돕니다." } },
  { id: 'impossible', name: 'Impossible', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, videoUrl: 'https://www.youtube.com/watch?v=WzzhO6fBqsc', description: { EN: "Wrap the board vertically around your back foot.", KR: "보드가 뒷발을 감싸듯이 360도 회전하는 기술입니다." } },
  { id: 'casper-flip', name: 'Casper Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, videoUrl: 'https://www.youtube.com/watch?v=tm6wP-CFJxk&t=17s', description: { EN: "Half kickflip, catch upside down with back foot, flip back.", KR: "반쯤 킥플립 후 뒷발로 보드를 뒤집힌 채로 받아 다시 돌려놓는 기술입니다." } },
  { id: 'full-cab', name: 'Full Cab', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "Fakie backside 360.", KR: "페이키 상태에서 백사이드로 360도 회전합니다." } },
  { id: 'half-cab-flip', name: 'Half Cab Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "Half Cab mixed with a kickflip.", KR: "하프캡을 하면서 킥플립을 넣는 기술입니다." } },
  { id: 'bigspin-flip', name: 'Bigspin Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.HARD, description: { EN: "Bigspin mixed with a kickflip.", KR: "빅스핀을 하면서 킥플립을 넣는 기술입니다." } },
  { id: 'feeble', name: 'Feeble Grind', category: TrickCategory.GRIND, difficulty: Difficulty.HARD, description: { EN: "Back truck grinds while front truck hangs over the rail.", KR: "뒷 트럭을 걸고 앞 트럭은 레일 너머로 넘겨서 그라인드합니다." } },
  { id: 'smith', name: 'Backside Smith', category: TrickCategory.GRIND, difficulty: Difficulty.HARD, description: { EN: "Back truck grinds while front truck hangs down the side.", KR: "뒷 트럭을 걸고 앞부분은 아래로 떨어뜨린 채 그라인드합니다." } },
  { id: 'crooked', name: 'Crooked Grind', category: TrickCategory.GRIND, difficulty: Difficulty.HARD, description: { EN: "Grind on the nose with the board angled out.", KR: "노즈로 그라인드하며 보드를 바깥쪽으로 비스듬히 둡니다." } },

  // Pro (Expert)
  { id: 'dolphin-flip', name: 'Dolphin Flip (Forward Flip)', category: TrickCategory.FLATGROUND, difficulty: Difficulty.PRO, description: { EN: "Board flips vertically forward between legs.", KR: "보드가 다리 사이에서 수직으로 앞으로 튀어나가며 도는 기술입니다." } },
  { id: 'hospital-flip', name: 'Hospital Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.PRO, description: { EN: "Half kickflip, catch with front foot, wrap around.", KR: "킥플립 반 바퀴 후 앞발로 보드를 잡아 돌리는 기술입니다." } },
  { id: 'double-kickflip', name: 'Double Kickflip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.PRO, description: { EN: "Kickflip that spins twice.", KR: "공중에서 보드가 두 바퀴 도는 킥플립입니다." } },
  { id: 'nightmare-flip', name: 'Nightmare Flip', category: TrickCategory.FLATGROUND, difficulty: Difficulty.PRO, description: { EN: "Varial double kickflip.", KR: "바리엘 플립인데 킥플립 회전이 두 번 들어갑니다." } },
  { id: 'overcrook', name: 'Overcrook', category: TrickCategory.GRIND, difficulty: Difficulty.PRO, description: { EN: "Crooked grind but over the other side of the rail.", KR: "크룩드 그라인드보다 더 깊게, 레일 반대편으로 넘겨서 그라인드합니다." } },
  { id: 'bluntslide', name: 'Bluntslide', category: TrickCategory.GRIND, difficulty: Difficulty.PRO, description: { EN: "Slide on the tail with wheels on top of the ledge.", KR: "테일을 수직으로 세워 렛지 위로 올리고 슬라이드합니다." } },
  { id: 'noseblunt', name: 'Nosebluntslide', category: TrickCategory.GRIND, difficulty: Difficulty.PRO, description: { EN: "Slide on the nose with wheels on top of the ledge.", KR: "노즈를 수직으로 세워 렛지 위로 올리고 슬라이드합니다." } },
];

export const TRICK_TIPS_DB: Record<string, TrickTip[]> = {
  "Ollie": [
    { text: { EN: "Pop HARD with your ankle, not your leg.", KR: "다리가 아닌 발목 스냅으로 강하게 팝을 차세요." }, source: "Pro Coach" },
    { text: { EN: "Slide your front foot all the way to the nose.", KR: "앞발을 노즈 끝까지 확실하게 끌어올리세요." }, source: "Community" }
  ],
  "Kickflip": [
    { text: { EN: "Flick out, not down.", KR: "아래가 아니라 대각선 밖으로 플릭하세요." }, source: "Pro Coach" },
    { text: { EN: "Keep your shoulders parallel to the board.", KR: "어깨가 보드와 평행이 되도록 유지하세요." }, source: "Community" }
  ]
  // ... (More tips can be added here)
};